services:
  dev:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
        - USER_NAME=${USER_NAME}
        - MAIN_LOCAL_DIR=${MAIN_LOCAL_DIR}
        - USER_HOME=${USER_HOME}
        - MAIN_DIR=${MAIN_DIR}
        - DEV_DIR=${DEV_DIR}
    environment:
      - MONGO_URL=mongodb://mongo:27018/juriscrape
      - TJ_API_URL=http://dev:3000
      - TJAL_ESAJ_URL=http://dev:3008
      - TJCE_ESAJ_URL=http://dev:3009
    env_file:
      - path: .env
        required: true
    volumes:
      # - /tmp:/tmp:rw
      - ~/.zsh_history:${USER_HOME}/.zsh_history:rw
      - ${MAIN_LOCAL_DIR}:${MAIN_DIR}/:rw
    networks:
      - webnet
    depends_on:
      - mongo
    tty: true

  mongo:
    image: mongo:4.4
    command: mongod --port 27018
    ports:
      - '27018:27018'
    container_name: juriscrape-mongo-dev
    volumes:
      - ./.mongo_data:/data/db
    networks:
      - webnet

networks:
  webnet:

volumes:
  .mongo_data: